var GAMES = [
    {
        id: 1,
        title: "Blitz Storm Arena",
        category: "action",
        badge: "featured",
        icon: "\u26A1",
        gradient: "linear-gradient(135deg, #1a1a4e, #0d47a1)",
        iconBg: "linear-gradient(135deg, #00b0ff, #7b2fff)",
        rating: 4.9,
        shortDesc: "Intense multiplayer battle arena with electrifying combat and power-ups.",
        fullDesc: "Step into the ultimate battle arena where lightning-fast reflexes meet strategic gameplay. Fight through waves of enemies, unlock powerful abilities, and dominate the leaderboard.",
        features: ["Real-time PvP Battles", "20+ Unique Characters", "Ranked Matchmaking", "Daily Challenges", "Epic Power-ups", "Global Leaderboards"],
        playStoreUrl: "#"
    },
    {
        id: 2,
        title: "Block Fusion",
        category: "puzzle",
        badge: "popular",
        icon: "\ud83e\uddca",
        gradient: "linear-gradient(135deg, #1b2838, #2d4059)",
        iconBg: "linear-gradient(135deg, #00e5ff, #2979ff)",
        rating: 4.7,
        shortDesc: "Merge colorful blocks in this addictive brain-teasing puzzle adventure.",
        fullDesc: "Block Fusion combines satisfying merging mechanics with challenging puzzle designs. Match, merge, and create powerful combinations through hundreds of handcrafted levels.",
        features: ["500+ Puzzle Levels", "Daily Brain Challenges", "Power-up Combos", "Relaxing Soundtrack", "Offline Play", "No Ads Mode"],
        playStoreUrl: "#"
    },
    {
        id: 3,
        title: "Crystal Cascade",
        category: "puzzle",
        badge: "new",
        icon: "\ud83d\udc8e",
        gradient: "linear-gradient(135deg, #1a0033, #4a148c)",
        iconBg: "linear-gradient(135deg, #e040fb, #7c4dff)",
        rating: 4.8,
        shortDesc: "Match and cascade glowing crystals through enchanted gem-filled worlds.",
        fullDesc: "Embark on a magical journey through crystalline realms. Match glowing gems, trigger spectacular cascades, and unlock mystical powers with stunning visual effects.",
        features: ["300+ Magical Levels", "Stunning VFX", "Boss Crystal Battles", "Collection System", "Weekly Events", "Cloud Save"],
        playStoreUrl: "#"
    },
    {
        id: 4,
        title: "Disc Strike Arena",
        category: "action",
        badge: "popular",
        icon: "\ud83e\udd4f",
        gradient: "linear-gradient(135deg, #1b3a1b, #1b5e20)",
        iconBg: "linear-gradient(135deg, #00e676, #00b0ff)",
        rating: 4.6,
        shortDesc: "Fast-paced disc throwing combat in neon-lit futuristic arenas.",
        fullDesc: "Master disc combat in futuristic neon arenas. Curve throws, bounce discs off walls, and outsmart opponents in this physics-based action game.",
        features: ["Physics-based Combat", "Neon Arenas", "Trick Shots System", "1v1 & 2v2 Modes", "Custom Discs", "Replay System"],
        playStoreUrl: "#"
    },
    {
        id: 5,
        title: "LudoQuest",
        category: "board",
        badge: "popular",
        icon: "\ud83c\udfb2",
        gradient: "linear-gradient(135deg, #3e1a00, #bf360c)",
        iconBg: "linear-gradient(135deg, #ff9100, #ff3d00)",
        rating: 4.8,
        shortDesc: "The classic board game reimagined with quests, powers, and online play.",
        fullDesc: "LudoQuest supercharges the beloved classic with RPG quests, special dice powers, and seamless online multiplayer. Play with friends or match worldwide.",
        features: ["Online Multiplayer", "Quest Mode", "Special Dice Powers", "Voice Chat", "Tournaments", "Custom Boards"],
        playStoreUrl: "#"
    },
    {
        id: 6,
        title: "Mystic Runner",
        category: "action",
        badge: "featured",
        icon: "\ud83c\udfc3",
        gradient: "linear-gradient(135deg, #0d1b2a, #1b3a5c)",
        iconBg: "linear-gradient(135deg, #18ffff, #00e5ff)",
        rating: 4.7,
        shortDesc: "Endless runner through mystical lands with magical abilities and obstacles.",
        fullDesc: "Run through enchanted forests, ancient temples, and mystical realms. Dodge obstacles, collect artifacts, and use supernatural powers to survive.",
        features: ["Infinite Procedural Levels", "6 Mystical Worlds", "Power-up Magic", "Daily Runs", "Pet Companions", "Achievement System"],
        playStoreUrl: "#"
    },
    {
        id: 7,
        title: "Phantom Strike",
        category: "action",
        badge: "new",
        icon: "\ud83d\udc7b",
        gradient: "linear-gradient(135deg, #1a1a2e, #16213e)",
        iconBg: "linear-gradient(135deg, #7b2fff, #e040fb)",
        rating: 4.9,
        shortDesc: "Stealth action game where you become the ultimate shadow warrior.",
        fullDesc: "Become the Phantom. Sneak through guarded fortresses, eliminate targets with precision, and vanish without a trace. Pure stealth action perfection.",
        features: ["30 Stealth Missions", "Shadow Abilities", "Stealth Ranking", "Multiple Endings", "Weapon Arsenal", "New Game Plus"],
        playStoreUrl: "#"
    },
    {
        id: 8,
        title: "Precision Shot",
        category: "arcade",
        badge: "popular",
        icon: "\ud83c\udfaf",
        gradient: "linear-gradient(135deg, #1a0000, #b71c1c)",
        iconBg: "linear-gradient(135deg, #ff1744, #ff9100)",
        rating: 4.5,
        shortDesc: "Test your aim in this challenging precision shooting arcade game.",
        fullDesc: "How precise is your aim? Challenge yourself with difficult targets, moving obstacles, and trick shots. Compete globally for the highest accuracy.",
        features: ["100+ Target Challenges", "Trick Shot Modes", "Global Accuracy Board", "Slow Motion Replays", "Custom Crosshairs", "Weekly Tournaments"],
        playStoreUrl: "#"
    },
    {
        id: 9,
        title: "Roll Master Quest",
        category: "board",
        badge: "new",
        icon: "\ud83c\udfb0",
        gradient: "linear-gradient(135deg, #1a1a00, #827717)",
        iconBg: "linear-gradient(135deg, #ffd600, #ff6d00)",
        rating: 4.6,
        shortDesc: "Roll dice through epic quest boards with RPG-style progression.",
        fullDesc: "Roll Master Quest combines dice rolling with RPG adventure. Travel across quest boards, fight monsters, collect loot, and level up your character.",
        features: ["RPG Progression", "50+ Quest Boards", "Monster Battles", "Loot Collection", "Character Classes", "Co-op Mode"],
        playStoreUrl: "#"
    },
    {
        id: 10,
        title: "Royal Dice Empire",
        category: "board",
        badge: "featured",
        icon: "\ud83d\udc51",
        gradient: "linear-gradient(135deg, #1a0a2e, #4a148c)",
        iconBg: "linear-gradient(135deg, #ffd700, #ff6f00)",
        rating: 4.8,
        shortDesc: "Build your empire one dice roll at a time in this strategy board game.",
        fullDesc: "Rule the realm with dice! Build cities, raise armies, forge alliances, and conquer territories where every roll shapes your empire destiny.",
        features: ["Empire Building", "Strategic Dice Combat", "Alliance System", "World Conquest Map", "Royal Court", "Seasonal Events"],
        playStoreUrl: "#"
    },
    {
        id: 11,
        title: "Serpent Surge",
        category: "arcade",
        badge: "new",
        icon: "\ud83d\udc0d",
        gradient: "linear-gradient(135deg, #003300, #1b5e20)",
        iconBg: "linear-gradient(135deg, #00e676, #76ff03)",
        rating: 4.4,
        shortDesc: "Modern twist on the classic snake game with surge powers and neon arenas.",
        fullDesc: "The classic snake reborn! Surge through neon grids, activate power-ups, battle other serpents, and grow to dominate the arena.",
        features: ["Neon Grid Arenas", "Surge Power-ups", "Battle Royale Mode", "Skin Customization", "Speed Challenges", "Retro & Modern Modes"],
        playStoreUrl: "#"
    },
    {
        id: 12,
        title: "Turbo Trail Racer",
        category: "racing",
        badge: "featured",
        icon: "\ud83c\udfce\ufe0f",
        gradient: "linear-gradient(135deg, #1a0000, #c62828)",
        iconBg: "linear-gradient(135deg, #ff1744, #f50057)",
        rating: 4.7,
        shortDesc: "Blazing fast racing through stunning trails with turbo boost mechanics.",
        fullDesc: "Feel the speed! Race through mountain trails, neon cities, and desert canyons. Master turbo boosts, drift through hairpin turns, and leave rivals in dust.",
        features: ["20+ Racing Tracks", "Turbo Boost System", "Car Customization", "Multiplayer Racing", "Career Mode", "Drift Challenges"],
        playStoreUrl: "#"
    }
];
